import { ArrowUpRight, ArrowRight } from '@phosphor-icons/react';

export const guidePath='/guides/vr-steering-wheel-unreal/';
export default function SteeringGuide() {
 return <main id="main" className="steering-guide">
  <header className="guide-heading section-pad"><p className="cinema-eyebrow">Playframe field notes / Unreal Engine 5.8</p><h1>A steering wheel<br />you can reach for.</h1><p>Set up physical VR steering in the Playframe Car Template, then align the seat, wheel and animated hands to your own vehicle.</p><span>Practical guide · 15 September 2026 · Playframe</span></header>
  <figure className="guide-image section-pad"><img src="/assets/templates/car-cockpit.webp" width="1280" height="720" alt="Controller-driven hands holding the car's steering wheel in Unreal Engine"/><figcaption>Actual in-engine capture. The hands follow tracked controllers; this is not optical hand tracking.</figcaption></figure>
  <div className="guide-body section-pad"><aside><span>IN THIS GUIDE</span><a href="#start">01 / Start from the demo</a><a href="#seat">02 / Align the seat</a><a href="#wheel">03 / Fit the wheel</a><a href="#hands">04 / Refine the grip</a><a href="#test">05 / Test the interaction</a></aside><article>
   <p className="guide-lead">A convincing VR wheel needs more than a rotating mesh. Your seated viewpoint, the wheel's interaction frame and the hand grip all need to agree. Start with a working car, change one setting at a time, and test from the headset.</p>
   <p>This walkthrough uses the <a href="/templates/vr-car-template/">Playframe VR Car Template</a> for Unreal Engine 5.8. You need the plugin installed and an OpenXR headset with tracked controllers. The supplied demo supports desktop testing; physical grabbing needs VR Preview or a VR build.</p>
   <section id="start"><h2>01 / Start from the working demo.</h2><p>Enable the plugin and its required built-in dependencies, then restart Unreal. Chaos Vehicles remains required even when you use the custom physics mode.</p><ol><li>Enable <strong>Show Plugin Content</strong> in the Content Browser.</li><li>Open <code>VR Car Template Content / Demo / Maps / L_CarPlayground</code>.</li><li>Press Play to check the default vehicle first. The map uses <code>BP_CarGameMode</code>, <code>BP_SportsCar</code> and <code>CarPlayerController</code>.</li><li>Create a child Blueprint of <code>BP_SportsCar</code> in your own project. Duplicate the handling and presentation Data Assets and assign the copies to your car. Make changes there.</li></ol><p>The supplied game mode configures its input automatically. You do not need to change project-wide input classes or add Default Mapping Context entries for this path.</p></section>
   <section id="seat"><h2>02 / Put the driver in the right place.</h2><p>Select <strong>VRControls</strong> in your child Blueprint and adjust <strong>Seat Eye Position</strong>. This position is in chassis space, in centimetres: +X is forward, +Y is right and +Z is up.</p><p>Connect the headset before starting Unreal, choose VR Preview, sit comfortably and look forward. Press <strong>A while stopped</strong> to recenter. The right stick's vertical axis can adjust seated height while stopped.</p><p>Adjusting the desktop <code>CockpitCamera</code> does not change VR recentering. Use Seat Eye Position for the headset, then test the same comfortable sitting position after each change.</p></section>
   <section id="wheel"><h2>03 / Match the interaction to the rim.</h2><p>For a replacement skeletal mesh, set the <strong>Steering Bone</strong> in your Presentation asset. Orient <strong>Steering Frame Rotation</strong> so local X runs along the steering shaft and local Y/Z span the rim. The visible wheel and VR interaction use this frame.</p><div className="guide-table"><table><thead><tr><th>VRControls setting</th><th>What to adjust</th></tr></thead><tbody><tr><td>Wheel Radius Cm</td><td>Match the radius of the visible rim, rather than its diameter.</td></tr><tr><td>Grab Tolerance Cm</td><td>How close a hand must be to engage a grip.</td></tr><tr><td>Wheel Lock Degrees</td><td>Maximum steering-wheel rotation in each direction.</td></tr></tbody></table></div><p><strong>Max Steer Degrees</strong> in the Handling asset controls the front road wheels. It is a different setting from the rotation of the wheel in your hands.</p></section>
   <section id="hands"><h2>04 / Make the grip look natural.</h2><p>Bring a controller-driven hand near the rim and squeeze its grip. Move either or both gripped hands around the wheel to steer. Keep the supplied hand component class when using the included hands.</p><ul><li><strong>Grip Lift Degrees</strong> moves the neutral left/right grip positions around the rim.</li><li><strong>Grip Palm Tilt Degrees</strong> adjusts the closed palm's angle against the wheel.</li><li><strong>Grip Depth Offset Cm</strong> moves the hand into or out of the rim.</li></ul><p>Change one parameter, restart Play and inspect both hands at centre and near full lock. Do not use a large grab tolerance to hide an incorrectly aligned wheel frame.</p><p>If you replace the hands, retarget to the supplied Epic mannequin XR bone convention or provide a compatible Animation Blueprint and expected joints. Arbitrary hand rigs need additional integration; swapping only the visible mesh is not sufficient.</p></section>
   <section id="test"><h2>05 / Test the whole interaction.</h2><ol><li>At rest, grab with one hand, then both. Turn left and right and check grip alignment.</li><li>Use the right trigger to accelerate and the left trigger to brake, then reverse. Test at low speed first.</li><li>Release and grab again. Check both Chaos and custom physics modes; <strong>Y</strong> switches modes on Quest Touch.</li><li>Test recentering while stopped and recovery after tracking loss. Tracking loss or lost VR focus releases grips and applies braking.</li><li>Let both triggers return to neutral after recentering or tracking recovery. Re-establish tracking and deliberately grab again.</li></ol><p>Finally test in a packaged build on your target headset. PCVR and standalone Quest have different rendering budgets, and a good desktop result does not establish standalone performance.</p></section>
   <section className="guide-next"><h2>Try the wheel before you build.</h2><p>The car page includes the Windows and Quest demos, actual footage, the full customization guide and the Fab listing.</p><a className="vehicle-button" href="/templates/vr-car-template/">Explore the VR Car Template <ArrowUpRight aria-hidden="true"/></a><a className="text-link" href="/templates/">See the full collection <ArrowRight aria-hidden="true"/></a></section>
   <p className="guide-source">Based on the VR Car Template User and Customization Guide, version 1.0.0, sections 1–4 and 7–9. <a href="https://drive.google.com/file/d/1UH5C71CRkPyH5RU9J0d41gd9NAmk5-yE/view" target="_blank" rel="noreferrer">Read the complete guide</a>.</p>
  </article></div>
 </main>;
}
